# Generated by Django 5.1.2 on 2025-08-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('case_id', models.IntegerField(blank=True, null=True)),
                ('numner_old', models.CharField(blank=True, max_length=45, null=True)),
                ('numner_new', models.IntegerField(blank=True, null=True)),
                ('comment_old', models.TextField(blank=True, null=True)),
                ('comment_new', models.TextField(blank=True, null=True)),
                ('kore_old', models.CharField(blank=True, max_length=255, null=True)),
                ('kore_new', models.CharField(blank=True, max_length=255, null=True)),
                ('inscribe_old', models.CharField(blank=True, db_column='Inscribe_old', max_length=255, null=True)),
                ('google_search', models.CharField(blank=True, max_length=255, null=True)),
                ('tlo_old', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KserviceRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('t_date', models.DateField(blank=True, null=True)),
                ('akuser_id', models.IntegerField(blank=True, null=True)),
                ('portfolio_lender', models.CharField(blank=True, max_length=255, null=True)),
                ('borrower_name', models.CharField(blank=True, max_length=255, null=True)),
                ('origination_date', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('origination_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('salesforce_ticket_number', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('business_structure', models.CharField(blank=True, max_length=255, null=True)),
                ('kore', models.CharField(blank=True, max_length=255, null=True)),
                ('inscribe', models.CharField(blank=True, db_column='Inscribe', max_length=255, null=True)),
                ('google_search', models.CharField(blank=True, max_length=255, null=True)),
                ('tlo', models.CharField(blank=True, max_length=255, null=True)),
                ('case_status', models.CharField(blank=True, max_length=45, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('application_loan_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
